---
resources:
- name: code
  type: git
  source:
    uri: https://github.com/mathias-ewald/hello-goose
    branch: master

- name: demo
  type: git
  source:
    uri: https://github.com/mathias-ewald/concourse-demo
    branch: master

jobs:
- name: build
  plan:
  - in_parallel:
    - get: code
    - get: demo
  - task: maven-package
    file: demo/tasks/maven-package/task.yml
