---
resources:
- name: code
  type: git
  source:
    uri: https://github.com/mathias-ewald/hello-goose
    branch: master

- name: tasks
  type: git
  source:
    uri: https://github.com/mathias-ewald/concourse-demo
    branch: master

jobs:
- name: build
  plan:
  - in_parallel:
    - get: code
    - get: tasks 
