---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: mewald@pivotal.io
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - selector:
        dnsZones:
          - "gcp.halusky.de"
      dns01:
        clouddns:
          project: cso-pcfs-emea-mewald
          serviceAccountSecretRef:
            name: clouddns-dns01-solver-svc-acct
            key: key.json
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: mewald@pivotal.io
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - selector:
        dnsZones:
          - "gcp.halusky.de"
      dns01:
        clouddns:
          project: cso-pcfs-emea-mewald
          serviceAccountSecretRef:
            name: clouddns-dns01-solver-svc-acct
            key: key.json
